Build and upload s390x-unknown-linux-gnu crate_universe binary to releases (#3462)
When building envoy on s390x, I get an error when trying to download the
cargo-bazel binary because it is not published to github releases (see
example message below).

This PR adds s390x-unknown-linux-gnu to the list of targets to release.

Error message:

```bash
ERROR: /home/jalbrecht/.cache/bazel/_bazel_jalbrecht/6fade89f6c57252e6093cc46d35caeb2/external/rules_rust/crate_universe/private/generate_utils.bzl:60:13: An error occurred during the fetch of repository 'dynamic_modules_rust_sdk_crate_index':
   Traceback (most recent call last):
        File "/home/jalbrecht/.cache/bazel/_bazel_jalbrecht/6fade89f6c57252e6093cc46d35caeb2/external/rules_rust/crate_universe/private/crates_repository.bzl", line 28, column 48, in _crates_repository_impl
                generator, generator_sha256 = get_generator(repository_ctx, host_triple.str)
        File "/home/jalbrecht/.cache/bazel/_bazel_jalbrecht/6fade89f6c57252e6093cc46d35caeb2/external/rules_rust/crate_universe/private/generate_utils.bzl", line 60, column 13, in get_generator
                fail((
Error in fail: No generator URL was found either in the `CARGO_BAZEL_GENERATOR_URL` environment variable or for the `s390x-unknown-linux-gnu` triple in the `generator_urls` attribute
ERROR: Error computing the main repository mapping: no such package '@@dynamic_modules_rust_sdk_crate_index//': No generator URL was found either in the `CARGO_BAZEL_GENERATOR_URL` environment variable or for the `s390x-unknown-linux-gnu` triple in the `generator_urls` attribute
```